### ISSUE TITLE
Error "unexpected upstream response" in Trickster

### ISSUE THREAD

**Issue by vuxuanlai** [tricksterproxy/trickster#504]
Hi there,
I'm using Trickster as proxy between grafana and prometheus k8s as flow:
Client -> grafana -> trickster (k8s) -> prometheus (k8s)
I got error log of trickster as below:
```
time=2020-10-14T07:15:21.960054181Z app=trickster caller=proxy/engines/deltaproxycache.go:378 level=error event="unexpected upstream response" statusCode=400
time=2020-10-14T07:16:52.80614017Z app=trickster caller=proxy/engines/deltaproxycache.go:378 level=error event="unexpected upstream response" statusCode=400
time=2020-10-14T07:16:52.854986772Z app=trickster caller=proxy/engines/deltaproxycache.go:378 level=error event="unexpected upstream response" statusCode=400
time=2020-10-14T07:16:52.903716578Z app=trickster caller=proxy/engines/deltaproxycache.go:378 level=error event="unexpected upstream response" statusCode=400
```

Could someone give me the reason and a solution to resolve?
Thanks

**Comment by jranson** [comment]
@vuxuanlai unfortunately we can't troubleshoot every user's specific situation, and this looks like user configuration error rather than a defect. These log entries indicate the upstream prometheus deployment is returning `400 Bad Request` to Trickster, so you will need to figure out what is configured incorrectly in your setup (e.g., domain names/paths in the Trickster and Grafana configs) .

**Comment by vuxuanlai** [comment]
Hi @jranson ,
This is my trickster value.yaml:
```
origins:
  - name: default
    originType: prometheus
    originURL: http://<prometheus-IP>
    timeoutSecs: "60"
    keepAliveTimeoutSecs: "180"
    
image:
  repository: tricksterproxy/trickster
  tag: "latest"
  pullPolicy: IfNotPresent

```
